name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: symfony_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=3

    env:
      DATABASE_URL: mysql://root:root@127.0.0.1:3306/symfony_test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP 8.2
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, intl, pdo_mysql
        tools: composer

    - name: Install Composer dependencies
      run: rm composer.lock && composer install --prefer-dist --no-progress --no-suggest --no-interaction

    - name: Create .env.test.local
      run: |
        echo 'DATABASE_URL="mysql://root:root@127.0.0.1:3306/symfony_test"' > .env.test.local

    - name: Run database migrations
      run: php bin/console

  analyze-static-code:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP 8.2 and tools for static analysis
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, intl, pdo_mysql
        tools: phpstan

    - name: Install dependencies
      run:  rm composer.lock && composer install --prefer-dist --no-progress --no-suggest --no-interaction

    - name: Run static analysis
      run: vendor/bin/phpstan analyse ./public/index.php

  run-unit-tests:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP 8.2 and PHPUnit
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, intl, pdo_mysql
        tools: phpunit

    - name: Install dependencies
      run:  rm composer.lock && composer install --prefer-dist --no-progress --no-suggest --no-interaction

    - name: Run unit tests
      run: vendor/bin/phpunit

  security-scan:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Symfony CLI
      run: |
        curl -sS https://get.symfony.com/cli/installer | bash
        sudo mv /home/runner/.symfony5/bin/symfony /usr/local/bin/symfony

    - name: Run security analysis
      run: symfony check:security
